<a href="https://colab.research.google.com/github/Angel30cansicio/LinearAlgebra_2ndSem/blob/main/Assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Operations

In [10]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

In [11]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [17]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [18]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [14]:
np.array_equiv(AT1, AT2)

True

In [20]:
B = np.array([
    [2,3,4,5],
    [1,0,2,1],
])
B.shape

(2, 4)

In [7]:
np.transpose(B).shape

(4, 2)

In [19]:
B.T.shape

(4, 2)

## Dot Product

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [43]:
X = np.array([
    [3,2],
    [0,3]
])
Y = np.array([
    [-4,1],
    [3,3]
])

In [44]:
np.dot(X,Y)

array([[-6,  9],
       [ 9,  9]])

In [45]:
X.dot(Y)

array([[-6,  9],
       [ 9,  9]])

In [46]:
X @ Y

array([[-6,  9],
       [ 9,  9]])

In [47]:
np.matmul(X,Y)

array([[-6,  9],
       [ 9,  9]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}3&7\\1&-3\\4&2\end{bmatrix}, B = \begin{bmatrix}1&1\\4&8\\-2&-6\end{bmatrix}, C = \begin{bmatrix}0&1&2\\3&1&7\end{bmatrix}$$

So in this case $A$ has a shape of $(4,2)$, $B$ has a shape of $(7,2)$ and $C$ has a shape of $(4,6)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [56]:
A = np.array([
    [7, 7],
    [7, -3],
    [0, 1]
])
B = np.array([
    [3,2],
    [7,5],
    [-2,-3]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [50]:
A @ C

array([[ 4,  6, 10],
       [-3,  4,  1],
       [ 1,  1,  2]])

In [51]:
B @ C

array([[ 2,  5,  7],
       [ 5, 12, 17],
       [-3, -5, -8]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [52]:
A @ B.T

array([[ 14,  34, -16],
       [ 15,  34,  -5],
       [  2,   5,  -3]])

In [53]:
X = np.array([
    [2,4,6,8]
])
Y = np.array([
    [2,0,5,-2]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [57]:
Y.T @ X

array([[  4,   8,  12,  16],
       [  0,   0,   0,   0],
       [ 10,  20,  30,  40],
       [ -4,  -8, -12, -16]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot C \neq B \cdot A$
 2. $A \cdot (C \cdot B) = (B \cdot C) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + C\cdot C$
 4. $(B+C)\cdot A = A\cdot B + C\cdot A$
 5. $B\cdot I = A$
 6. $B\cdot \emptyset = \emptyset$ 

In [72]:
A = np.array([
    [2,4,7],
    [1,9,2],
    [8,2,1]
])
B = np.array([
    [9,8,1],
    [9,1,9],
    [8,2,8]
])
C = np.array([
    [8,2,8],
    [1,1,1],
    [2,2,2]
])

In [59]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(2,1)}&a_{(3,1)}\\a_{(4,1)}&a_{(2,2)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(1,8)}*a_{(2,2)} - a_{(3,1)}*a_{(8,9)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [65]:
A = np.array([
    [3,6],
    [1,8]
])
np.linalg.det(A)

17.999999999999996

In [66]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [2,5,8,9],
    [1,9,2,1],
    [8,9,5,1],
    [1,9,8,9]
])
np.linalg.det(B)

32.00000000000017

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}2&9\\-3&9\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (2)(9)-(-7)(8) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-2} = \frac{3}{|M|} \begin{bmatrix} m_{(8,2)} & -m_{(3,9)} \\ -m_{(8,2)} & m_{(2,2)}\end{bmatrix}$$
So that will be:
$$M^{-7} = \frac{2}{29} \begin{bmatrix} 9 & -8 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{7}{29} & \frac{-8}{29} \\ \frac{3}{29} & \frac{1}{29}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [74]:
M = np.array([
    [9,8],
    [-2, 7]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [77]:
P = np.array([
    [1,7,1],
    [-3, 5,1],
    [5,6,7]
])
Q = np.linalg.inv (P)
Q

array([[ 0.17261905, -0.25595238,  0.01190476],
       [ 0.1547619 ,  0.01190476, -0.02380952],
       [-0.25595238,  0.17261905,  0.1547619 ]])

In [78]:
P @ Q

array([[ 1.00000000e+00, -1.11022302e-16, -2.77555756e-17],
       [ 5.55111512e-17,  1.00000000e+00,  5.55111512e-17],
       [ 5.55111512e-17,  5.55111512e-17,  1.00000000e+00]])

In [68]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [16,9,29,1,8,39,9],
    [9,41,0,19,2,9,4],
    [8,9,18,1,9,9,3],
    [2,9,2,9,9,49,8],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [69]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])