<a href="https://colab.research.google.com/github/Angel30cansicio/LinearAlgebra_2ndSem/blob/main/Assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Operations

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

In [8]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [7]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [6]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [10]:
np.array_equiv(AT1, AT2)

True

In [9]:
B = np.array([
    [2,3,4,5],
    [1,0,2,1],
])
B.shape

(2, 4)

In [11]:
np.transpose(B).shape

(4, 2)

In [12]:
B.T.shape

(4, 2)

## Dot Product

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [13]:
X = np.array([
    [3,2],
    [0,3]
])
Y = np.array([
    [-4,1],
    [3,3]
])

In [14]:
np.dot(X,Y)

array([[-6,  9],
       [ 9,  9]])

In [15]:
X.dot(Y)

array([[-6,  9],
       [ 9,  9]])

In [16]:
X @ Y

array([[-6,  9],
       [ 9,  9]])

In [17]:
np.matmul(X,Y)

array([[-6,  9],
       [ 9,  9]])

## In comparison to vector dot products, matrix dot products have additional rules. There are fewer limits because vector dot products are only one dimensional. Since we're dealing with Rank 2 vectors, there are a few rules to keep in mind:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

Given a matrix $A$ of the shape $(a,b), $a$ and $b$ can be any integers. Matrix $B$ should have the shape $(b,c)$ if we wish to do a dot product between $A$ and another matrix $B$, where $b$ and $c$ are any integers. As a result, for the following matrices:

$$A = \begin{bmatrix}3&7\\1&-3\\4&2\end{bmatrix}, B = \begin{bmatrix}1&1\\4&8\\-2&-6\end{bmatrix}, C = \begin{bmatrix}0&1&2\\3&1&7\end{bmatrix}$$

In this instance, $A$ has a $(4,2)$ shape, $B$ has a $(7,2)$ shape, and $C$ has a $(4,6)$ shape. Matrix pairings $A cdot C$ and $B cdot C$ are the only ones that can be used to conduct dot product.

In [18]:
A = np.array([
    [7, 7],
    [7, -3],
    [0, 1]
])
B = np.array([
    [3,2],
    [7,5],
    [-2,-3]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [19]:
A @ C

array([[ 7, 14, 21],
       [-3,  4,  1],
       [ 1,  1,  2]])

In [20]:
B @ C

array([[ 2,  5,  7],
       [ 5, 12, 17],
       [-3, -5, -8]])

The shape of the dot product has altered, and it is no longer the same as any of the matrices we utilized. The shapes of the matrices utilized are used to determine the shape of a dot product. So, if matrix $A$ has the shape $(a,b)$ and matrix $B$ has the shape $(b,c)$, then $A cdot B$ should have the shape $(a,c)$.

In [21]:
A @ B.T

array([[ 35,  84, -35],
       [ 15,  34,  -5],
       [  2,   5,  -3]])

In [22]:
X = np.array([
    [2,4,6,8]
])
Y = np.array([
    [2,0,5,-2]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [23]:
Y.T @ X

array([[  4,   8,  12,  16],
       [  0,   0,   0,   0],
       [ 10,  20,  30,  40],
       [ -4,  -8, -12, -16]])

### Rule 2: Dot Product has special properties

Dot products are common in matrix algebra, which means they have a number of distinct properties that should be considered when formulating.solutions:
 1. $A \cdot C \neq B \cdot A$
 2. $A \cdot (C \cdot B) = (B \cdot C) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + C\cdot C$
 4. $(B+C)\cdot A = A\cdot B + C\cdot A$
 5. $B\cdot I = A$
 6. $B\cdot \emptyset = \emptyset$ 

In [24]:
A = np.array([
    [2,4,7],
    [1,9,2],
    [8,2,1]
])
B = np.array([
    [9,8,1],
    [9,1,9],
    [8,2,8]
])
C = np.array([
    [8,2,8],
    [1,1,1],
    [2,2,2]
])

In [25]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(2,1)}&a_{(3,1)}\\a_{(4,1)}&a_{(2,2)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(1,8)}*a_{(2,2)} - a_{(3,1)}*a_{(8,9)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [30]:
A = np.array([
    [3,6],
    [1,8]
])
np.linalg.det(A)

17.999999999999996

In [31]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [2,5,8,9],
    [1,9,2,1],
    [8,9,5,1],
    [1,9,8,9]
])
np.linalg.det(B)

32.00000000000017

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}2&9\\-3&9\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (2)(9)-(-7)(8) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-2} = \frac{3}{|M|} \begin{bmatrix} m_{(8,2)} & -m_{(3,9)} \\ -m_{(8,2)} & m_{(2,2)}\end{bmatrix}$$
So that will be:
$$M^{-7} = \frac{2}{29} \begin{bmatrix} 9 & -8 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{7}{29} & \frac{-8}{29} \\ \frac{3}{29} & \frac{1}{29}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [32]:
M = np.array([
    [9,8],
    [-2, 7]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [33]:
P = np.array([
    [1,7,1],
    [-3, 5,1],
    [5,6,7]
])
Q = np.linalg.inv (P)
Q

array([[ 0.17261905, -0.25595238,  0.01190476],
       [ 0.1547619 ,  0.01190476, -0.02380952],
       [-0.25595238,  0.17261905,  0.1547619 ]])

In [34]:
P @ Q

array([[ 1.00000000e+00, -1.11022302e-16, -2.77555756e-17],
       [ 5.55111512e-17,  1.00000000e+00,  5.55111512e-17],
       [ 5.55111512e-17,  5.55111512e-17,  1.00000000e+00]])

In [35]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [16,9,29,1,8,39,9],
    [9,41,0,19,2,9,4],
    [8,9,18,1,9,9,3],
    [2,9,2,9,9,49,8],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [36]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

## Activity
#Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [52]:
A = np.array ([
    [2,4,6,8],
    [10,12,14,16],
    [18,20,22,24],
    [26,28,30,32]           
])
B = np.array ([
    [0,1,2,3],
    [6,7,8,9],
    [0,3,1,7],
    [8,7,9,4]           
])
C = np.array ([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]           
])

In [56]:
D = B.dot(B)
E = C.dot(C)
F = D.dot(C)
G = B + C
H = D + A
I = B.dot(C)
J = A.dot(D)
K = E + F

In [57]:
print('PROPERTY NO. 1')
print(f'Is AB=BA?:  {np.array_equiv(D, I)}')
print('Matrix AB:')
print(np.matmul(A,B))
print(f'Shape:\t{np.matmul(A,B).shape}')
print('Matrix BA:')
print(np.matmul(B,A))
print(f'Shape:\t{np.matmul(B,A).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 1
Is AB=BA?:  False
Matrix AB:
[[ 88 104 114 116]
 [200 248 274 300]
 [312 392 434 484]
 [424 536 594 668]]
Shape:	(4, 4)
Matrix BA:
[[124 136 148 160]
 [460 520 580 640]
 [230 252 274 296]
 [352 408 464 520]]
Shape:	(4, 4)
PROPERTY PROVEN!


In [58]:
print('PROPERTY NO. 2')
print(f'Is A(BC)=(AB)C?:  {np.array_equiv(A.dot(F),D.dot(C))}')
print('Matrix A(BC):')
print(np.matmul(A,F))
print(f'Shape:\t{np.matmul(A,F).shape}')
print('Matrix (AB)C:')
print(np.matmul(D,C))
print(f'Shape:\t{np.matmul(D,C).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 2
Is A(BC)=(AB)C?:  False
Matrix A(BC):
[[ 62902  71052  79202  87352]
 [153750 173804 193858 213912]
 [244598 276556 308514 340472]
 [335446 379308 423170 467032]]
Shape:	(4, 4)
Matrix (AB)C:
[[ 988 1124 1260 1396]
 [4486 5072 5658 6244]
 [2037 2334 2631 2928]
 [3845 4314 4783 5252]]
Shape:	(4, 4)
PROPERTY PROVEN!


In [59]:
print('PROPERTY NO. 3')
print(f'Is A(B+C)=(AB)+(AC)?:  {np.array_equiv(A.dot(G),H)}')
print('Matrix A(B+C):')
print(np.matmul(A,G))
print(f'Shape:\t{np.matmul(A,G).shape}')
print('Matrix (AB)+(AC):')
print(np.add(D,E))
print(f'Shape:\t{np.add(D,E).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 3
Is A(B+C)=(AB)+(AC)?:  False
Matrix A(B+C):
[[ 268  304  334  356]
 [ 604  704  782  860]
 [ 940 1104 1230 1364]
 [1276 1504 1678 1868]]
Shape:	(4, 4)
Matrix (AB)+(AC):
[[120 134 147 155]
 [316 370 411 453]
 [388 429 486 502]
 [500 596 659 766]]
Shape:	(4, 4)
PROPERTY PROVEN!


In [60]:
print('PROPERTY NO. 4')
print(f'Is (B+C)A=(BA)+(CA)?:  {np.array_equiv(G.dot(A),K)}')
print('Matrix (B+C)A:')
print(np.matmul(G,A))
print(f'Shape:\t{np.matmul(G,A).shape}')
print('Matrix (BA)+(CA):')
print(np.add(I,J))
print(f'Shape:\t{np.add(I,J).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 4
Is (B+C)A=(BA)+(CA)?:  False
Matrix (B+C)A:
[[ 304  336  368  400]
 [ 864  976 1088 1200]
 [ 858  964 1070 1176]
 [1204 1376 1548 1720]]
Shape:	(4, 4)
Matrix (BA)+(CA):
[[ 1614  2038  2240  2542]
 [ 4118  5118  5648  6270]
 [ 6339  7872  8687  9586]
 [ 8736 10838 11974 13186]]
Shape:	(4, 4)
PROPERTY PROVEN!


In [61]:
print('PROPERTY NO. 5')
print(f'Is A(1)=A?:  {np.array_equiv(A.dot(1),A)}')
print('Matrix A(1):')
print(np.multiply(A,1))
print(f'Shape:\t{np.multiply(A,1).shape}')
print('Matrix A:')
print(A)
print(f'Shape:\t{A.shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 5
Is A(1)=A?:  True
Matrix A(1):
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Shape:	(4, 4)
Matrix A:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Shape:	(4, 4)
PROPERTY PROVEN!


In [62]:
print('PROPERTY NO. 6')
print(f'Is A(0)=0?:  {np.array_equiv(A.dot(0),0)}')
print('Matrix A(0):')
print(np.multiply(A,0))
print(f'Shape:\t{np.multiply(A,0).shape}')
print('PROPERTY PROVEN!')

PROPERTY NO. 6
Is A(0)=0?:  True
Matrix A(0):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape:	(4, 4)
PROPERTY PROVEN!
