<a href="https://colab.research.google.com/github/Angel30cansicio/LinearAlgebra_2ndSem/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Laboratory 4 Matrices

# Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

# Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them. A matrix is a type of two-dimensional array in which each data piece has the same size. As a result, every matrix is also a two-dimensional array, but not the other way around. Matrices are crucial data structures for a wide range of mathematical and scientific calculations.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-2x+3y-4z \\
        3w- x -2y +2 \\
        2w -x + 3y - 2z
    \end{array}
\right. $$




A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix}1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}
$$

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


In [4]:
## since we'll keep on describing matrices. Let's make a function
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [5]:
## Declaring a 2 x 2 matrix
A = np.array ([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [6]:
## Declaring a 3 x 2 matrix
B = np.array ([
    [1, 2],
    [3, 1],
    [5, 8]
])
describe_mat(B)

Matrix:
[[1 2]
 [3 1]
 [5 8]]

Shape:	(3, 2)
Rank:	2



## Categorizing Matrices
Row and Column Matrices

We define a row and column matrix in this code by using np.array, which adds strong data structures to Python that ensure rapid calculations with arrays and matrices, as well as a large library of high-level mathematical functions that operate on these arrays and matrices. A matrix can be implemented as a nested list in Python (list inside a list). Each element is regarded as a matrix row. Columns are the designations we assign to the two dimensions of a matrix or more by convention.

In [7]:
## Declaring a Row Matrix

row_mat_1D = np.array ([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix
row_mat_2D = np.array ([
    [1,2,3,-4]
]) ## this is a 2
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [8]:
## Declaring a Column Matrix

col_mat = np.array ([
    [3], 
    [5], 
    [1]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[3]
 [5]
 [1]]

Shape:	(3, 1)
Rank:	2



## Square Matrices
A matrix is a rectangular data or number structure. It's a rectangular array of data or numbers, in other words. In a matrix, the horizontal entries are referred to as 'rows,' while the vertical elements are referred to as 'columns.'


In [9]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs square: {is_square}\n')

In [10]:
square_mat = np.array ([
   [3,5,1],
   [1,2,3],
   [1,5,9]                     
])

non_square_mat = np.array ([
   [3,5,2],
   [1,2,4]                   
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[3 5 1]
 [1 2 3]
 [1 5 9]]

Shape:	(3, 3)
Rank:	2
Is square: True

Matrix:
[[3 5 2]
 [1 2 4]]

Shape:	(2, 3)
Rank:	2
Is square: False



## Null Matrix
In a relational database, a null value is used when a column's value is unknown or missing. A null value is neither an empty string nor a zero value (for character or datetime data types) (for numeric data types). It's a unique object that symbolizes the lack of a value. A None is returned by any function that does not return anything.

In [11]:
def describe_mat(matrix):
    if matrix.size > 0:
      is_square = True if matrix.shape[0] == matrix.shape[1] else False
      print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
      print('Matrix is Null')

In [12]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


## Zero Matrix
Simple solutions to algebraic equations involving matrices are possible with Zero Matrices. The zero matrix, for example, can be defined as an additive group, making it a useful variable in situations when an unknown matrix must be solved.


In [13]:
zero_mat_row = np.zeros ((1,2))
zero_mat_sqr = np.zeros ((2,2))
zero_mat_rct = np.zeros ((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangle Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangle Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
ones_mat_row =np.ones ((2,3))
ones_mat_sqr= np.ones((3,3,))
ones_mat_rct=np.ones ((4,3))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangle Matrix: \n{ones_mat_row}')

Ones Row Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ones Rectangle Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]


## Diagonal Matrix
Many parts of linear algebra use diagonal matrices. Because of the above-mentioned straightforward description of the matrix operation and eigenvalues/eigenvectors, a diagonal matrix is commonly used to describe a given matrix or linear map. We can extract a diagonal element from a matrix and output it as a one-dimensional matrix.

In [15]:
np.array ([
  [3,5,1],
  [0,3,1],
  [7,8,9]         
])

array([[3, 5, 1],
       [0, 3, 1],
       [7, 8, 9]])

In [16]:
d = np.diag([2,3,4,5])
d.shape[0]==d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

## Identity Matrix
A squared matrix (infinite ratio of rows and columns) with all diagonal values equal to 1 is an identity matrix. All of the other spots, on the other hand, have a value of 0. The NumPy identity() method assists us with this and delivers an identity matrix as asked.

In [17]:
np.eye (3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Upper Triangular Matrix
All entries below the significant diagonal are zero in the upper triangular matrix. A suitable triangular matrix is the upper triangular matrix, whereas a left triangular matrix is the lower triangular matrix.

In [19]:
np.array([
  [2,3,4,5],
  [1,1,8,1],
  [0,0,8,0],
  [0,0,0,3]
])

array([[2, 3, 4, 5],
       [1, 1, 8, 1],
       [0, 0, 8, 0],
       [0, 0, 0, 3]])

## Lower Triangular Matrix
A lower triangular matrix has entries that are zero above the main diagonal. Lower triangular matrices are also known as left triangular matrices. Lower triangular matrices are square matrices with zero entries above the main diagonal.

In [20]:
np.array([
    [1,0,0],
    [5,3,0],
    [3,5,1]      

])

array([[1, 0, 0],
       [5, 3, 0],
       [3, 5, 1]])

In [21]:
np.array([
    [1,0,0],
    [5,3,0],
    [3,5,1]      

])

array([[1, 0, 0],
       [5, 3, 0],
       [3, 5, 1]])

## Practice 1
1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$



$$
\theta = \begin{bmatrix} 5  &  3 & -1\end{bmatrix} \\
$$

```



In [22]:
def describe_mat (matrix):
 print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [23]:
theta = np.array ([
  [5,3,-1]
])
describe_mat (theta)

Matrix:
[[ 5  3 -1]]

Shape:	(1, 3)
Rank:	2



2. Given the system of linear combinations below, try to encode it is amatrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


In [24]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [25]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs square: {is_square}\n')

In [26]:
A = np.array ([
   [1,2,1],
   [0,4,-1],
   [0,0,10]                     
])

describe_mat(A)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is square: True



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown



In [27]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

$$
G = \begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}
$$

$$
G = \left\{
    \begin{array}\
        1 + 7 + 8 \\
        2 + 2 + 2 \\
        4 + 6 + 7 \\
    \end{array}
\right. \\
 $$

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [28]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

In [29]:
([[1,0,0],
  [2,2,0],
  [4,6,7]])

[[1, 0, 0], [2, 2, 0], [4, 6, 7]]

$$
H = \begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix}
$$

$$
H = \left\{
    \begin{array}\
        1 + 0 + 0 \\
        2 + 2 + 0 \\
        4 + 6 + 7 \\
    \end{array}
\right. \\
 $$

## Matrix Algebra
Addition
They are adding two matrices by adding the corresponding elements together, known as matrix addition in mathematics. However, other operations for matrices, such as the direct sum and the Kronecker sum, can also be termed addition.

In [30]:
A = np.array([
    [1,2],
    [3,4],           
    [6,7]
])
B = np.array([
    [2,2],
    [0,4],           
    [5,1]              
])
A+B

array([[ 3,  4],
       [ 3,  8],
       [11,  8]])

In [31]:
3+A ##Broadcasting

array([[ 4,  5],
       [ 6,  7],
       [ 9, 10]])

## Subtraction
If two matrices have the same order or dimensions, they can be subtracted. To subtract two or more matrices, they must each have the same number of rows and columns. If the elements of two matrices are in the same order, subtracting one from the other is feasible.

In [32]:
A = np.array([
    [1,2],
    [3,4],           
    [6,7]
])
B = np.array([
    [2,2],
    [0,4],           
    [5,1]              
])
A-B

array([[-1,  0],
       [ 3,  0],
       [ 1,  6]])

In [33]:
6-B ##Broadcasting

array([[4, 4],
       [6, 2],
       [1, 5]])

## Element-wise Multiplication
Elements of the first matrix are multiplied by the corresponding component of the second matrix in element-wise matrix multiplication (also known as Hadamard Product). Each matrix must be of the exact dimensions when doing element-wise matrix multiplication.

In [34]:
A*B

array([[ 2,  4],
       [ 0, 16],
       [30,  7]])

In [35]:
4*A

array([[ 4,  8],
       [12, 16],
       [24, 28]])

## Activity 2


## Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [36]:
import numpy as np
X = int(input("Number of rows:"))
Y = int(input("Number of columns:")) 
print("Elements per row (values will be separatade by space): ")  
entries = list(map(int, input().split()))
matrix = np.array(entries).reshape(X, Y)
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'\nMatrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}')
describe_mat(matrix)
is_empty = matrix == 0
if False:
  print('The matrix is empty')
else:
   print('The matrix is not empty')

point=0
for m in range(len(matrix)):
    for s in range(len(matrix[0])):
        if m == s and matrix[m][s] != 1:
            point=1
            break
        elif m!=s and matrix[m][s]!=0:
            point=1
            break
arr = matrix
is_all_zero = np.all((arr == 0))
if is_all_zero:
    print('The matrix only have 0')
else:
    print('The matrix has non-zero items')

arr = matrix
is_all_zero = np.all((arr == 1))
if is_all_zero:
    print('The matrix only have 1')
else:
    print('The matrix non-ones items')

Number of rows:1
Number of columns:1
Elements per row (values will be separatade by space): 
1

Matrix:
[[1]]

Shape:	(1, 1)
Rank:	2
Is Square: True
The matrix is not empty
The matrix has non-zero items
The matrix only have 1


## Function

In [ ]:
## Function

In [ ]:
## Matrix Declarations

In [ ]:
## Test Areas

## Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.
Returns the sum of the matrices.
Returns the differen of the matrices.
Returns the element-wise multiplication of the matrices.
Returns the element-wise division of the matrices.
Use 3 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [37]:
import numpy as np
def mat_operation(a,b):
  r1=len(a)
  r2=len(b)
  c1=len(a[0])
  c2=len(b[0])
  if r1!=r2 and c1!=c2 :
    return "Operation not possible"
  #Compute the sum of the array
  s=[[0]*c1]*r1
  d=[[0]*c1]*r1
  p=[[0]*c1]*r1
  d=[[0]*c1]*r1
  for i in range(r1):
    for j in range(c1):
      s[i][j]=a[i][j]+b[i][j]
      d[i][j]=a[i][j]-b[i][j]
      p[i][j]=a[i][j]*b[i][j]
      d[i][j]=a[i][j]/b[i][j]
  return [s,d,p,d]
#generate the 2 random matrices
x =  np.random.randint(100, size=(3, 3))
y =  np.random.randint(100, size=(3, 3))
print("x= ",x)
print("y= ",y)
[s,d,p,d]=mat_operation(x,y)
print("x+y",s)
print("x-y",d)
print("x*y",p)
print("x/y",d)

x=  [[56 66  9]
 [89 37 27]
 [20 33 46]]
y=  [[36 15 41]
 [78 92 48]
 [ 6 94 22]]
x+y [[26, 127, 68], [26, 127, 68], [26, 127, 68]]
x-y [[3.3333333333333335, 0.35106382978723405, 2.090909090909091], [3.3333333333333335, 0.35106382978723405, 2.090909090909091], [3.3333333333333335, 0.35106382978723405, 2.090909090909091]]
x*y [[120, 3102, 1012], [120, 3102, 1012], [120, 3102, 1012]]
x/y [[3.3333333333333335, 0.35106382978723405, 2.090909090909091], [3.3333333333333335, 0.35106382978723405, 2.090909090909091], [3.3333333333333335, 0.35106382978723405, 2.090909090909091]]


## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?"