<a href="https://colab.research.google.com/github/Angel30cansicio/LinearAlgebra_2ndSem/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Laboratory 4 Matrices

# Discussion

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

# Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        w-2x+3y-4z \\
        3w- x -2y +2 \\
        2w -x + 3y - 2z
    \end{array}
\right. $$




A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix}1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}
$$

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We are-

In [4]:
## since we'll keep on describing matrices. Let's make a function
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [5]:
## Declaring a 2 x 2 matrix
A = np.array ([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [6]:
## Declaring a 3 x 2 matrix
B = np.array ([
    [1, 2],
    [3, 1],
    [5, 8]
])
describe_mat(B)

Matrix:
[[1 2]
 [3 1]
 [5 8]]

Shape:	(3, 2)
Rank:	2



## Categorizing Matrices
Row and Column Matrices

In [7]:
## Declaring a Row Matrix

row_mat_1D = np.array ([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix
row_mat_2D = np.array ([
    [1,2,3,-4]
]) ## this is a 2
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [8]:
## Declaring a Column Matrix

col_mat = np.array ([
    [3], 
    [5], 
    [1]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[3]
 [5]
 [1]]

Shape:	(3, 1)
Rank:	2



## Square Matrices

In [9]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs square: {is_square}\n')

In [10]:
square_mat = np.array ([
   [3,5,1],
   [1,2,3],
   [1,5,9]                     
])

non_square_mat = np.array ([
   [3,5,2],
   [1,2,4]                   
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[3 5 1]
 [1 2 3]
 [1 5 9]]

Shape:	(3, 3)
Rank:	2
Is square: True

Matrix:
[[3 5 2]
 [1 2 4]]

Shape:	(2, 3)
Rank:	2
Is square: False



## Null Matrix

In [11]:
def describe_mat(matrix):
    if matrix.size > 0:
      is_square = True if matrix.shape[0] == matrix.shape[1] else False
      print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
      print('Matrix is Null')

In [12]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


## Zero Matrix

In [13]:
zero_mat_row = np.zeros ((1,2))
zero_mat_sqr = np.zeros ((2,2))
zero_mat_rct = np.zeros ((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangle Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangle Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


A ones matrix

In [14]:
ones_mat_row =np.ones ((2,3))
ones_mat_sqr= np.ones((3,3,))
ones_mat_rct=np.ones ((4,3))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangle Matrix: \n{ones_mat_row}')

Ones Row Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]
Ones Square Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ones Rectangle Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]]


## Diagonal Matrix

In [15]:
np.array ([
  [3,5,1],
  [0,3,1],
  [7,8,9]         
])

array([[3, 5, 1],
       [0, 3, 1],
       [7, 8, 9]])

In [16]:
d = np.diag([2,3,4,5])
d.shape[0]==d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

## Identity Matrix

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Upper Triangular Matrix

In [19]:
np.array([
  [2,3,4,5],
  [1,1,8,1],
  [0,0,8,0],
  [0,0,0,3]
])

array([[2, 3, 4, 5],
       [1, 1, 8, 1],
       [0, 0, 8, 0],
       [0, 0, 0, 3]])

## Lower Triangular Matrix

In [21]:
np.array([
    [1,0,0],
    [5,3,0],
    [3,5,1]      

])

array([[1, 0, 0],
       [5, 3, 0],
       [3, 5, 1]])

In [22]:
np.array([
    [1,0,0],
    [5,3,0],
    [3,5,1]      

])

array([[1, 0, 0],
       [5, 3, 0],
       [3, 5, 1]])

## Activity 1
1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$


2. Given the system of linear combinations below, try to encode it is amatrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown



In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

## Matrix Algebra
Addition

In [ ]:
A = np.array([
    [1,2],
    [3,4],           
    [6,7]
])
B = np.array([
    [2,2],
    [0,4],           
    [5,1]              
])
A+B

array([[ 3,  4],
       [ 3,  8],
       [11,  8]])

In [ ]:
3+A ##Broadcasting

array([[ 4,  5],
       [ 6,  7],
       [ 9, 10]])

## Subtraction

In [ ]:
A = np.array([
    [1,2],
    [3,4],           
    [6,7]
])
B = np.array([
    [2,2],
    [0,4],           
    [5,1]              
])
A-B

array([[-1,  0],
       [ 3,  0],
       [ 1,  6]])

In [ ]:
6-B ##Broadcasting

array([[4, 4],
       [6, 2],
       [1, 5]])

## Element-wise Multiplication

In [ ]:
A*B

array([[ 2,  4],
       [ 0, 16],
       [30,  7]])

In [ ]:
4*A

array([[ 4,  8],
       [12, 16],
       [24, 28]])

## Activity 2


## Task 1

Create a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

## Function

In [ ]:
## Function

In [ ]:
## Matrix Declarations

In [ ]:
## Test Areas

## Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.
Returns the sum of the matrices.
Returns the differen of the matrices.
Returns the element-wise multiplication of the matrices.
Returns the element-wise division of the matrices.
Use 3 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?"